services:
  postgres:
    image: postgres:15-alpine
    container_name: spms_db
    environment:
      POSTGRES_USER: spms_user
      POSTGRES_PASSWORD: spms_password
      POSTGRES_DB: spms_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build: ./budget_backend
    container_name: spms_backend
    ports:
      - "5000:5000"
    environment:
      DB_HOST: postgres
      DB_USER: spms_user
      DB_PASSWORD: spms_password
      DB_NAME: spms_db
      DB_PORT: 5432
    depends_on:
      - postgres

  frontend:
    build: ./budget_frontend
    container_name: spms_frontend
    ports:
      - "80:80"
    depends_on:
      - backend

volumes:
  pgdata: